###

# curl -X POST -H "Content-Type: application/json" -d @/src/test/json_test_data/isInRegion/point_on_boundary.json https://localhost:8080/api/v1/distanceTo
POST http://localhost:8080/api/v1/isInRegion
Content-Type: application/json

< ../../json_test_data/IsInRegion/point_on_boundary.json

###